# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_city.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(531, 331)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(531, 331))
        Form.setMaximumSize(QtCore.QSize(531, 331))
        Form.setWindowOpacity(5.0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 311))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.checkBox_ped = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_ped.setChecked(True)
        self.checkBox_ped.setObjectName("checkBox_ped")
        self.verticalLayout_3.addWidget(self.checkBox_ped)
        self.checkBox_auto = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_auto.setChecked(True)
        self.checkBox_auto.setObjectName("checkBox_auto")
        self.verticalLayout_3.addWidget(self.checkBox_auto)
        self.checkBox_tram = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_tram.setChecked(True)
        self.checkBox_tram.setObjectName("checkBox_tram")
        self.verticalLayout_3.addWidget(self.checkBox_tram)
        self.checkBox_troll = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_troll.setChecked(True)
        self.checkBox_troll.setObjectName("checkBox_troll")
        self.verticalLayout_3.addWidget(self.checkBox_troll)
        self.checkBox_bike = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_bike.setChecked(True)
        self.checkBox_bike.setObjectName("checkBox_bike")
        self.verticalLayout_3.addWidget(self.checkBox_bike)
        self.checkBox_spec = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_spec.setChecked(True)
        self.checkBox_spec.setObjectName("checkBox_spec")
        self.verticalLayout_3.addWidget(self.checkBox_spec)
        self.checkBox_scooter = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_scooter.setChecked(True)
        self.checkBox_scooter.setObjectName("checkBox_scooter")
        self.verticalLayout_3.addWidget(self.checkBox_scooter)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_4.addWidget(self.radioButton_5)
        self.radioButton_10 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_4.addWidget(self.radioButton_10)
        spacerItem = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_4.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setObjectName("btn_stop")
        self.verticalLayout_4.addWidget(self.btn_stop)
        self.btn_reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout_4.addWidget(self.btn_reset)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Открытый город"))
        self.label.setText(_translate("Form", "Экскурсии"))
        self.checkBox_ped.setText(_translate("Form", "Пешеходные"))
        self.checkBox_auto.setText(_translate("Form", "Автобусные"))
        self.checkBox_tram.setText(_translate("Form", "Тармвайные"))
        self.checkBox_troll.setText(_translate("Form", "Троллейбусные"))
        self.checkBox_bike.setText(_translate("Form", "Велосипедные"))
        self.checkBox_spec.setText(_translate("Form", "Специальные"))
        self.checkBox_scooter.setText(_translate("Form", "На самокатах"))
        self.label_3.setText(_translate("Form", "Следующий запрос"))
        self.progressBar.setFormat(_translate("Form", "%p%"))
        self.label_2.setText(_translate("Form", "Пауза между\n"
"запросами"))
        self.radioButton_3.setText(_translate("Form", "3 минут"))
        self.radioButton_5.setText(_translate("Form", "5 минут"))
        self.radioButton_10.setText(_translate("Form", "10 минут"))
        self.btn_start.setText(_translate("Form", "Старт"))
        self.btn_stop.setText(_translate("Form", "Стоп"))
        self.btn_reset.setText(_translate("Form", "Сброс цвета"))

